//! kipio_account_generated
//!
//! Auto-generated by tools/export_rust_production.py.
//! Do not edit by hand.

#![allow(warnings, unconditional_panic)]
#![allow(nonstandard_style)]
#![cfg_attr(any(), rustfmt::skip)]

include!("generated/kipio_account_all.rs");
